language: ruby
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - dvipng

before_install:
  - gem update --system
  - gem update bundler

rvm:
##  - 2.0
  - 2.1
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.0
##  - ruby-head

branches:
  only:
    - master
